version: "3"
services:
  # php:
  #   container_name: php
  #   build:
  #     context: .
  #     dockerfile: docker/php/Dockerfile
  #   ports:
  #     - ${PHP_PORT}:9000
  #   volumes:
  #     - ${APP_PATH}:/var/www
  # composer:
  #   restart: "no"
  #   image: library/composer:1.10.6
  #   command: install
  #   volumes:
  #     - ${APP_PATH}:/app
  # nginx:
  #   container_name: nginx
  #   build:
  #     context: .
  #     dockerfile: docker/nginx/Dockerfile
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - ${APP_PATH}/public:/var/www/public
  #   depends_on:
  #     - php
  apache:
    container_name: apache
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
    ports:
      - ${APATCH_PORT}:80
    volumes:
      - ${APP_PATH}:/var/www/html:delegated
  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    ports:
      - ${MYSQL_PORT}:3306
