version: "3"

services:
  apache:
    container_name: ${APATCH_CONTAINER_NAME:-apache}
    build:
      context: .
      dockerfile: ./apache/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:-7.4}
    ports:
      - ${APATCH_PORT:-80}:80
    volumes:
      - ${APP_PATH}:/var/www/html:delegated
  mysql:
    platform: linux/x86_64
    container_name: ${MYSQL_CONTAINER_NAME:-mysql}
    build:
      context: .
      dockerfile: mysql/Dockerfile
      args:
        MYSQL_VERSION: ${MYSQL_VERSION:-5.7}
    environment:
      MYSQL_DATABASE: ${MYSQL_NAME:-mysql}
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    ports:
      - ${MYSQL_PORT:-3306}:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/sql:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:mysql
    ports:
      - ${FORWARD_PMA_PORT}:8081
    environment:
      MYSQL_USERNAME: user
      MYSQL_ROOT_PASSWORD: password
      PMA_HOST: mysql
