version: "3"

services:
  apache:
    container_name: apache
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
    ports:
      - ${APATCH_PORT}:80
    volumes:
      - ${APP_PATH}:/var/www/html:delegated
  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    ports:
      - ${MYSQL_PORT}:3306
