version: "3"

services:
  web:
    container_name: ${APATCH_CONTAINER_NAME}
    build:
      context: .
      dockerfile: apache/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
    ports:
      - ${APATCH_PORT}:80
    volumes:
      - ${APP_PATH}:/var/www/html:delegated
  mysql:
    container_name: ${MYSQL_CONTAINER_NAME}
    build:
      context: .
      dockerfile: mysql/Dockerfile
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
    environment:
      MYSQL_DATABASE: db1
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Tokyo
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/sql:/docker-entrypoint-initdb.d
